---
ingress_nginx_manifest_url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.15.1/deploy/static/provider/cloud/deploy.yaml"
ingress_nginx_manifest_path: /tmp/ingress-nginx-deploy.yaml
